"""
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28.
The first ten terms would be:
1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
Let us list the factors of the first seven triangle numbers:
 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.
What is the value of the first triangle number to have over five hundred divisors?
"""

from utils import PrimeGen

import math

def factors(n):
    limit = int(math.sqrt(n))
    if n == 1:
        return [1]
    if n == 2:
        return [1, 2]

    fac = []
    for c in range(1, limit + 1):
        if n % c == 0:
            fac.append(c)
            # Not to duplicate
            if c != limit:
                fac.append(n // c)
        
    return fac

def triagle_nr_with_factors(over):
    triangle = 1
    l = 1

    while True:
        l += 1
        triangle += l

        n = len(factors(triangle))
        if n > over:
            return triangle


if __name__ == "__main__":
    print(triagle_nr_with_factors(500))
